[package]
name = "test_weights"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }

[lib]
name = "test_weights_rust"
crate-type = ["cdylib"]