[package]
name = "make_predictions_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
itertools = "0.10"
rayon = "1.7"
crossbeam = "0.8"

[lib]
name = "make_predictions_rust"
crate-type = ["cdylib"]